dbt_tutorial:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: password
      dbname: adventureworks
      schema: public
  target: dev
